version: '3.8'

services:
  # Serviço PHP (não muda)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jyotish-api-php

  # Serviço Nginx (simplificado e sem healthcheck)
  nginx:
    image: nginx:alpine
    container_name: jyotish-api-nginx
    ports:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/jyotish.conf
      - ./api:/var/www/html
    depends_on:
      - php
