version: '3.8'

services:
  # Serviço PHP
  php:
    # Constrói a imagem usando o Dockerfile que já criamos
    build:
      context: .
      dockerfile: Dockerfile
    # O nome do contêiner não é estritamente necessário, mas é uma boa prática
    container_name: jyotish-api-php

  # Serviço Nginx
  nginx:
    # Usa uma imagem oficial do Nginx
    image: nginx:alpine
    # Nome do contêiner
    container_name: jyotish-api-nginx
    # Mapeia a porta 80 do Nginx para a porta que o Coolify vai acessar.
    # Usaremos a porta 80, o padrão para web.
    ports:
      - "80" # Coolify vai se conectar a esta porta
    # Monta o volume com nosso arquivo de configuração
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Compartilha o código da aplicação com o Nginx para servir arquivos estáticos
      - ./api:/var/www/html
    # Garante que o serviço Nginx só inicie depois do serviço PHP
    depends_on:
      - php
