version: '3.8'

services:
  # Serviço PHP (não muda)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jyotish-api-php

  # Serviço Nginx (agora com build em pasta separada)
  nginx:
    build:
      context: ./nginx # <-- A MUDANÇA CRÍTICA: Aponta para a nova pasta
    container_name: jyotish-api-nginx
    ports:
      - "80"
    volumes:
      # Não precisamos mais montar o nginx.conf, pois ele já foi copiado no build.
      # Mantemos este volume para que o Nginx possa servir arquivos estáticos se precisar.
      - ./api/public:/var/www/html/public
    depends_on:
      - php
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/api/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
