{\rtf1\ansi\ansicpg1252\cocoartf2821
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 version: '3.8'\
\
services:\
  # Servi\'e7o PHP (n\'e3o muda)\
  php:\
    build:\
      context: .\
      dockerfile: Dockerfile\
    container_name: jyotish-api-php\
\
  # Servi\'e7o Nginx (agora com build em pasta separada)\
  nginx:\
    build:\
      context: ./nginx # <-- A MUDAN\'c7A CR\'cdTICA: Aponta para a nova pasta\
    container_name: jyotish-api-nginx\
    ports:\
      - "80"\
    volumes:\
      # N\'e3o precisamos mais montar o nginx.conf, pois ele j\'e1 foi copiado no build.\
      # Mantemos este volume para que o Nginx possa servir arquivos est\'e1ticos se precisar.\
      - ./api/public:/var/www/html/public\
    depends_on:\
      - php\
    healthcheck:\
      test: ["CMD-SHELL", "wget -qO- http://localhost/api/ping || exit 1"]\
      interval: 10s\
      timeout: 5s\
      retries: 5}